import { mockUserService } from "./mockUserService";
import { userService as uService } from "./userService";
import { friendService as fService } from "./friendService";
import { IUserService } from "./IUserService";
import { IFriendService } from "./IFriendService";
import { mockFriendService } from "./mockFriendService";
import { postService as pService } from "./postService";
import {config} from 'dotenv';
import { IPostService } from "./IPostService";
config();
export const userService: IUserService = uService;
export const friendService:IFriendService =fService;
export const postService:IPostService = pService;