import { mockUserService } from "./mockUserService";
import { userService as userServiceProvider } from "./userService";
import { friendService as friendServiceProvider } from "./friendService";
import { IUserService } from "./IUserService";
import { IFriendService } from "./IFriendService";
import { mockFriendService } from "./mockFriendService";
import { postService as postServiceProvider } from "./postService";
import {config} from 'dotenv';
import { IPostService } from "./IPostService";
import { INotificationService } from "./INotificationService";
import {notificationService as notificationServiceProvider} from "./notificationService";
config();
export const userService: IUserService = userServiceProvider;
export const friendService:IFriendService =friendServiceProvider;
export const postService:IPostService = postServiceProvider;
export const notificationService:INotificationService = notificationServiceProvider;